name: MacOS

on:
  push:
    branches:
      - gen2
  pull_request:
    branches:
      - gen2

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        brew install libusb

    - name: configure
      run: cmake . -Bbuild

    - name: build
      run: cmake --build build --parallel
