name: Tidy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake . -Bbuild -DDEPTHAI_CLANG_TIDY=ON

    - name: Run clang-tidy
      run: cmake --build . --parallel
      