name: Ubuntu

on:
  push:
    branches:
      - gen2
  pull_request:
    branches:
      - gen2

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
        run: |
          apt install libusb-1.0-0-dev
          apt install libusb-1.0-0

    - name: configure
      run: cmake . -Bbuild

    - name: build
      run: cmake --build build --parallel
